// ==UserScript==
// @ScriptName        京东比价-推送版
// @Author            Cuttlefish
// @ScriptTime        2023-02-09
// @ConfigURL         https://github.com/wanghao6736/proxy-assets/raw/main/quantumult-x/rewrite/Function/JingDongPrice.conf
// ==/UserScript==


hostname = api.m.jd.com

# > 京东比价@githubdulong
^https?://api\.m\.jd\.com/(client\.action|api)\?functionId=(wareBusiness|serverConfig|basicConfig|lite_wareBusiness|pingou_item) url script-response-body https://github.com/wanghao6736/proxy-assets/raw/main/quantumult-x/js/jd_price_lite.js